#!/bin/sh
# postinst script for mosquitto
#
# see: dh_installdeb(1)

set -e

setup_mosquitto_user() {
	if ! getent passwd mosquitto >/dev/null; then
		adduser --quiet --system --no-create-home --home /var/run/mosquitto --shell /usr/sbin/nologin mosquitto
	fi
}

fix_permissions() {
	chown mosquitto /var/lib/mosquitto
	chown mosquitto /var/run/mosquitto
}

case "$1" in
	configure)
		sed -i 's!^#persistence_location.*!persistence_location /var/lib/mosquitto/!' /etc/mosquitto.conf
		sed -i 's!^#pid_file.*!pid_file /var/run/mosquitto/mosquitto.pid!' /etc/mosquitto.conf
		setup_mosquitto_user
		fix_permissions
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac


#DEBHELPER#

exit 0
