#!/bin/sh
# postinst script for mosquitto
#
# see: dh_installdeb(1)

set -e

setup_mosquitto_user() {
	if ! getent passwd mosquitto >/dev/null; then
		adduser --quiet --system --no-create-home --home /var/lib/mosquitto --shell /usr/sbin/nologin mosquitto
	fi
}

fix_permissions() {
	chown mosquitto /var/lib/mosquitto
	chown mosquitto /var/run/mosquitto
}

case "$1" in
	configure)
		setup_mosquitto_user
		fix_permissions

		if [ -f /var/lib/mosquitto/mosquitto.db ]; then
			mv /var/lib/mosquitto/mosquitto.db /var/lib/mosquitto/mosquitto.db.dpkg-old
		fi
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac


#DEBHELPER#

exit 0
